#!/bin/bash
## This template site for Ruby on Rails works on WSL Ubuntu (Version 2)
## Take user input to initialize project
read -p "Configure git? (y/n)" git_choice

if [[ "$git_choice" == "y" ]]
then
  read -p "Enter name for git global config: " user_name
  echo $user_name
  read -p "Enter github global config email: " email
  echo $email
  sudo apt-get install git
  # Configure Git
  git config --global color.ui true
  git config --global user.name "$user_name"
  git config --global user.email "$email"
fi

read -p "Configure SSH? (y/n)" ssh_choice
if [[ $"ssh_choice" == "y" ]]
then
  ssh-keygen -t rsa -b 4096 -C $email
fi

read -p "Enter the project name: " project_name
echo $project_name

## Install node, yarn, gcc, g++, and all required packages for rails
sudo apt install curl
curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
sudo apt-get install gcc g++ make -y
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
sudo apt-get update -y && sudo apt-get install yarn -y
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get update
sudo apt-get install zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common libffi-dev nodejs -y

git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
# exec $SHELL

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
# exec $SHELL

rbenv install 3.1.1
rbenv global 3.1.1

gem install bundler

## Install Rails
gem install rails -v 7.0.2.3
rbenv rehash
rails -v
## Set up the database wit Postgresql
### Create the file repository configuration:
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
### Import the repository signing key:
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
### Update the package lists:
sudo apt-get update
sudo apt-get upgrade
### Install the latest version of PostgreSQL.
### If you want a specific version, use 'postgresql-12' or similar instead of 'postgresql':
sudo apt-get -y install postgresql
sudo apt install libpq-dev
sudo /etc/init.d/postgresql start
## Set up new project in your project folder
rails new $project_name --database=postgresql --css tailwind
cd $project_name
# sudo vim /etc/postgresql/<VERSION>/main/postgresql.conf
# - Enable "listen_addresses"
sudo -u postgres createuser -s $USER
rake db:create

if [[ "$ssh_choice" == "y" ]]
then
  echo INPUT THIS KEY INTO YOUR TRUSTED GITHUB KEYS
  echo verify with this command: ssh -T git@github.com
  cat ~/.ssh/id_rsa.pub
fi
